version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8888:80
    # env_file:
    #   - ./backend/.env
    environment:
      - DATABASE_URL=sqlite:////db/metrics.db
    volumes:
      - ./assets/db:/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3333:3000